version: '3.9'

services:
  partners-gateway-service:
    image: nginx
    restart: unless-stopped
    ports:
      - 7000:80
      - 7001:443
    networks:
      partners-network:
        ipv4_address: 182.39.0.53
        aliases:
          - partners.local.com
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./gateway/certs:/etc/nginx/certs

  partners-cache-service:
    image: redis
    restart: always
    ports:
      - 7003:6379
    networks:
      partners-network:
        ipv4_address: 182.39.0.203
        aliases:
          - partners.cache.local.com
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data

  partners-api-service:
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    image: partners-api-service
    ports:
      - 7006:8080
      - 7007:9229
    networks:
        partners-network:
          ipv4_address: 182.39.0.172
          aliases:
            - partners.api.local.com
    restart: unless-stopped
    depends_on:
      - partners-gateway-service
      - partners-cache-service
    volumes:
    - .:/app
    - /app/node_modules
    container_name: partners-api-service
    command: npm run start:dev

volumes:
  cache:
    driver: local

networks:
  partners-network:
    ipam:
      driver: default
      config:
        - subnet: 182.39.0.0/16